apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
  - port: 27017
  selector:
    app: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
          name: web
        livenessProbe:
          exec:
            command: ['/usr/bin/mongo', '--eval', 'db.serverStatus()']
          initialDelaySeconds: 10
          timeoutSeconds: 10
        volumeMounts:
        - name: database
          mountPath: /data/db
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: mongo